version: '3'

services:
  api-bookhub:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: api-bookhub
    ports:
      - 3000:3000
    restart: always
    volumes:
      - .:/home/bookhub-api/app
    tty: true
    networks: 
      - bookhub-net

networks:
  bookhub-net:
    driver: bridge
